'use strict';
const fs=require('fs');const path=require('path');const http=require('http');const https=require('https');
const root=path.resolve(process.argv[2]||process.cwd());const registryPath=path.join(root,'dashboard/command-center/registry/module-registry.json');const outputPath=path.join(root,'reports/command-center/modules.json');
const readJson=p=>{try{return JSON.parse(fs.readFileSync(p,'utf8'));}catch{return null;}};const full=p=>path.join(root,p);const exists=p=>Boolean(p)&&fs.existsSync(full(p));const normalize=s=>String(s||'').toUpperCase().replace(/[\s-]+/g,'_');
const summarize=(id,data)=>{if(!data)return {status:'AVAILABLE',score:null,metric:'Evidence available'};if(id==='performance')return{status:normalize(data.overall?.recommendation||'PASS'),score:data.overall?.readinessScore??null,metric:`${Number(data.overall?.totalRequests||0).toLocaleString()} requests`};if(id==='trends')return{status:normalize(data.overallStatus||data.adjustedDecision?.recommendation||'PASS'),score:data.adjustedDecision?.readinessScore??null,metric:`Trend ${data.overallStatus||'available'}`};if(id==='playwright')return{status:normalize(data.result||'PASS'),score:data.successRate??null,metric:data.totalSteps!=null?`${data.passedSteps||0}/${data.totalSteps} steps`:'Web evidence available'};if(id==='release')return{status:normalize(data.recommendation||data.status||'PASS'),score:data.score??data.readinessScore??null,metric:'Release decision available'};if(id==='doctor')return{status:normalize(data.overallStatus||data.status||'PASS'),score:data.score??data.healthScore??null,metric:data.summary||'Doctor evidence available'};return{status:normalize(data.status||data.result||data.recommendation||'PASS'),score:data.score??null,metric:'Evidence available'};};
const ping=url=>new Promise(resolve=>{if(!url)return resolve(false);let done=false;const finish=v=>{if(!done){done=true;resolve(v)}};try{const u=new URL(url);const req=(u.protocol==='https:'?https:http).request(u,{method:'GET',timeout:1200},res=>{res.resume();finish(res.statusCode>=200&&res.statusCode<500)});req.on('timeout',()=>{req.destroy();finish(false)});req.on('error',()=>finish(false));req.end();}catch{finish(false)}});
const freshness=(report,live,staleAfterHours)=>{if(live)return{state:'LIVE',ageHours:0,label:'Live service'};if(!report||/^https?:/.test(report)||!exists(report))return{state:'UNKNOWN',ageHours:null,label:'Freshness unavailable'};const modified=fs.statSync(full(report)).mtime;const ageHours=(Date.now()-modified.getTime())/3600000;return{state:ageHours>staleAfterHours?'STALE':'CURRENT',ageHours:Number(ageHours.toFixed(1)),lastModified:modified.toISOString(),label:ageHours>staleAfterHours?`Stale · ${Math.round(ageHours)}h old`:`Updated ${ageHours<1?'<1':Math.round(ageHours)}h ago`};};
const context=()=>{const candidates=['reports/updr/summary.json','reports/updr-integrated/summary.json','performance/updr/reports/intelligence/performance-intelligence.json'];let data={};for(const p of candidates){const d=readJson(full(p));if(d){data={...data,...d};}}return{executionId:data.executionId||data.runId||data.correlationId||'LATEST',environment:data.environment||'demo',build:data.build||data.buildNumber||'local',release:data.release||data.releaseName||'UPDR',generatedAt:new Date().toISOString()};};
(async()=>{const registry=readJson(registryPath);if(!registry)throw new Error(`Cannot read ${registryPath}`);const staleAfterHours=Number(registry.staleAfterHours||72);const modules=[];for(const def of registry.modules){let report=def.report;if(report&&!/^https?:/.test(report)&&!exists(report))report=(def.alternates||[]).find(exists)||def.report;const reportAvailable=/^https?:/.test(report)?false:exists(report);const live=def.healthUrl?await ping(def.healthUrl):false;const data=def.summary?readJson(full(def.summary)):null;const summary=summarize(def.id,data);const fresh=freshness(report,live,staleAfterHours);let state='NOT_AVAILABLE';if(def.kind==='live')state=live?'LIVE':(reportAvailable?'STALE':'NOT_AVAILABLE');else if(reportAvailable||data)state=['FAIL','FAILED','NOT_READY','CRITICAL'].includes(summary.status)?'FAILED':(fresh.state==='STALE'?'STALE':'PASS');modules.push({...def,report,state,available:live||reportAvailable||Boolean(data),live,summary,freshness:fresh});}const model={contract:'mapaf.command-center.discovery/v2',generatedAt:new Date().toISOString(),context:context(),modules};fs.mkdirSync(path.dirname(outputPath),{recursive:true});fs.writeFileSync(outputPath,JSON.stringify(model,null,2));console.log(`MAPAF Command Center modules discovered: ${outputPath}`);console.log(JSON.stringify(Object.fromEntries(modules.map(m=>[m.id,m.state]))));})().catch(e=>{console.error(e.stack||e);process.exit(1)});
