package core.ai.generation;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class FeatureDocumentationWriter {

    public void write(
            AutomationFeaturePackage featurePackage,
            String featureDirectory
    ) {
        try {
            Path readmePath =
                    Path.of(
                            featureDirectory,
                            "README.md"
                    );

            Files.writeString(
                    readmePath,
                    buildReadme(featurePackage)
            );

        } catch (IOException e) {
            throw new RuntimeException(
                    "Failed to write feature README",
                    e
            );
        }
    }

    private String buildReadme(
            AutomationFeaturePackage featurePackage
    ) {
        AutomationProject project =
                featurePackage.getProject();

        return """
                # %s

                ## Overview

                This feature package was generated by MAPAF AI Automation Studio.

                ## Generated Files

                - GeneratedScreen.java
                - GeneratedFlow.java
                - GeneratedTest.java
                - ASSERTIONS.md
                - TEST_DATA.md
                - TODO_ITEMS.md

                ## Assertions

                %s

                ## Test Data

                %s

                ## TODO Items

                %s

                ## Manual Review Checklist

                - [ ] Replace TODO locators with real Appium locators
                - [ ] Validate generated Screen Object methods
                - [ ] Validate generated Business Flow logic
                - [ ] Validate generated TestNG test class
                - [ ] Replace placeholder test data
                - [ ] Run compile validation
                - [ ] Run relevant test suite

                ## Recommended Validation

                ```bash
                gradle clean compileTestJava
                ```
                """.formatted(
                featurePackage.getFeatureName(),
                project.getAssertions(),
                project.getTestData(),
                project.getTodoItems()
        );
    }
}
