plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.testng:testng:7.10.2'

    testImplementation 'io.appium:java-client:9.4.0'

    testImplementation 'org.apache.logging.log4j:log4j-api:2.24.3'
    testImplementation 'org.apache.logging.log4j:log4j-core:2.24.3'
    testImplementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.24.3'

    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'io.rest-assured:json-schema-validator:5.5.0'

    testImplementation 'io.qameta.allure:allure-testng:2.29.1'
}

tasks.withType(Test).configureEach {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useTestNG() {
        listeners.add("io.qameta.allure.testng.AllureTestNg")
    }

    systemProperty "allure.results.directory", "$buildDir/allure-results"

    outputs.upToDateWhen { false }
}

test {
    useTestNG() {
        suites 'testng.xml'
    }
}

tasks.register('apiTest', Test) {
    description = 'Runs API TestNG suite'
    group = 'verification'

    useTestNG() {
        suites 'testng-api.xml'
        listeners.add("io.qameta.allure.testng.AllureTestNg")
    }
}

tasks.register('mobileTest', Test) {
    description = 'Runs Mobile TestNG suite'
    group = 'verification'

    useTestNG() {
        suites 'testng-mobile.xml'
        listeners.add("io.qameta.allure.testng.AllureTestNg")
    }
}

tasks.register('regressionTest', Test) {
    description = 'Runs Regression TestNG suite'
    group = 'verification'

    useTestNG() {
        suites 'testng-regression.xml'
        listeners.add("io.qameta.allure.testng.AllureTestNg")
    }
}

tasks.register('iosTest', Test) {
    useTestNG() {
        suites 'testng-ios.xml'
    }
}