package dashboard.enterprise.agent.connector.tests;
import dashboard.enterprise.agent.connector.audit.*; import dashboard.enterprise.agent.connector.credential.EnvironmentCredentialResolver; import dashboard.enterprise.agent.connector.health.ConnectorHealthChecker; import dashboard.enterprise.agent.connector.model.*; import dashboard.enterprise.agent.connector.provider.*; import dashboard.enterprise.agent.connector.provider.azure.AzureDevOpsLiveConnectorProvider; import dashboard.enterprise.agent.connector.registry.*; import dashboard.enterprise.agent.connector.resolution.*; import dashboard.enterprise.agent.model.AgentContext; import dashboard.enterprise.agent.tool.PermissionLevel; import org.testng.Assert; import org.testng.annotations.Test;
import java.nio.file.*; import java.util.*;
public final class LiveEnterpriseConnectorFrameworkTest {
 @Test public void shouldReportLiveConnectorNotConfiguredWithoutSecrets(){var p=new AzureDevOpsLiveConnectorProvider("https://dev.azure.com/example",new EnvironmentCredentialResolver(Map.of()));Assert.assertEquals(p.health().status(),ConnectorStatus.NOT_CONFIGURED);}
 @Test public void shouldResolveReplayWhenLiveIsUnavailable() throws Exception {var replay=new ReplayEnterpriseConnectorProvider("azure-devops-replay","AZURE_DEVOPS",50,List.of("work-item.read"),Map.of("work-item.read",Map.of("key","RS-101")));var live=new AzureDevOpsLiveConnectorProvider("https://dev.azure.com/example",new EnvironmentCredentialResolver(Map.of()));var hybrid=new HybridEnterpriseConnectorProvider(live,replay);var registry=new InMemoryConnectorRegistry();registry.register(hybrid);var audit=new InMemoryConnectorAuditStore();var runtime=new ConnectorRuntime(new ConnectorResolver(registry),audit);var response=runtime.invoke(new AgentContext(Path.of("."),"CORR-22","tester",Map.of()),new ConnectorRequest("mapaf.connector.request/v1","REQ-1","work-item.read",Map.of()),"",PermissionLevel.READ_ONLY,false);Assert.assertTrue(response.successful());Assert.assertEquals(response.data().get("key"),"RS-101");Assert.assertEquals(audit.events().size(),1);}
 @Test(expectedExceptions=SecurityException.class) public void shouldRequireApprovalForWrites() throws Exception {var replay=new ReplayEnterpriseConnectorProvider("jira-replay","JIRA",50,List.of("work-item.create-draft"),Map.of());var registry=new InMemoryConnectorRegistry();registry.register(replay);new ConnectorRuntime(new ConnectorResolver(registry),new InMemoryConnectorAuditStore()).invoke(new AgentContext(Path.of("."),"CORR-23","tester",Map.of()),new ConnectorRequest("mapaf.connector.request/v1","REQ-2","work-item.create-draft",Map.of()),"",PermissionLevel.WRITE_WITH_APPROVAL,false);}
 @Test public void shouldPublishConnectorAuditEvidence() throws Exception {Path root=Files.createTempDirectory("mapaf-connector-audit");Path file=ConnectorAuditPublisher.publish(root,List.of(new ConnectorAuditEvent("mapaf.connector.audit/v1","now","corr","jira-replay","work-item.read","REPLAY","SUCCESS",Map.of())));Assert.assertTrue(Files.isRegularFile(file));Assert.assertTrue(Files.readString(file).contains("mapaf.connector.audit/v1"));}
}
