package dashboard.enterprise.details;

import com.fasterxml.jackson.databind.JsonNode;
import core.json.JsonMapper;

import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Renders capability-specific evidence as a reusable enterprise Evidence Hub.
 *
 * All links point to evidence already generated by the capability publishers.
 * This class does not create or mutate execution evidence.
 */
public final class EvidenceSectionRenderer {

    private EvidenceSectionRenderer() {
    }

    public static String render(String moduleKey, JsonNode root) {
        String key = moduleKey == null ? "" : moduleKey.toLowerCase();

        StringBuilder html = new StringBuilder("""
                <div class="evidence-hub">
                  <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:16px">
                    <div>
                      <div class="label">MAPAF Enterprise</div>
                      <h3 style="margin:5px 0">Evidence Hub</h3>
                      <p class="note" style="margin:0">Auditable execution evidence, diagnostics and engineering reports.</p>
                    </div>
                    <span class="badge">AVAILABLE</span>
                  </div>
                  <div class="grid">
                """);

        switch (key) {
            case "mobile" -> appendMobile(html, root);
            case "web" -> appendWeb(html, root);
            case "api" -> appendApi(html, root);
            case "performance" -> appendPerformance(html, root);
            default -> appendGeneric(html, key);
        }

        appendFailureIntelligence(html, key);
        appendAllure(html);
        appendRawSummary(html, key);

        return html.append("</div></div>").toString();
    }

    private static void appendMobile(StringBuilder html, JsonNode root) {
        int screenshots = root.path("screenshots").asInt(0);

        card(
                html,
                "📸",
                "Mobile Screenshots",
                screenshots > 0 ? screenshots + " captured" : "Available",
                "../../build/allure-report/index.html",
                "Open screenshots in Allure"
        );
        card(
                html,
                "📱",
                "Device Session",
                value(root, "device", "Android execution evidence"),
                "../../mobile/reports/enterprise-summary.json",
                "Open device session"
        );
        card(
                html,
                "🧭",
                "Workflow Telemetry",
                value(root, "finalWorkflowState", "Available"),
                "../../mobile/reports/enterprise-summary.json",
                "Open telemetry"
        );
        card(
                html,
                "🤖",
                "Locator Intelligence",
                healingSummary(root),
                "../../mobile/reports/enterprise-summary.json",
                "Open AI metadata"
        );
    }

    private static void appendWeb(StringBuilder html, JsonNode root) {
        int screenshots = root.path("screenshots").asInt(0);

        card(
                html,
                "📸",
                "Portal Screenshots",
                screenshots > 0 ? screenshots + " captured" : "Available",
                "../../web/reports/evidence-index.html",
                "Open screenshots"
        );
        card(
                html,
                "🎥",
                "Execution Video",
                value(root, "videoStatus", value(root, "video", "Generated")),
                "../../web/reports/evidence-index.html",
                "Open video artifacts"
        );
        card(
                html,
                "🌐",
                "Playwright Trace",
                value(root, "traceStatus", value(root, "trace", "Generated")),
                "../../web/reports/evidence-index.html",
                "Open trace artifacts"
        );
        card(
                html,
                "🖥️",
                "Browser Diagnostics",
                browserSummary(root),
                "../../web/reports/enterprise-summary.json",
                "Open diagnostics"
        );
        card(
                html,
                "📡",
                "Network Evidence",
                networkSummary(root),
                "../../web/reports/evidence-index.html",
                "Open network artifacts"
        );
    }

    private static void appendApi(StringBuilder html, JsonNode root) {
        int calls = root.path("apiCalls").asInt(0);

        card(
                html,
                "📤",
                "Request Payloads",
                calls > 0 ? calls + " API calls" : "Available",
                "../../api/reports/enterprise-summary.json",
                "Open requests"
        );
        card(
                html,
                "📥",
                "Response Payloads",
                payloadSummary(root),
                "../../api/reports/enterprise-summary.json",
                "Open responses"
        );
        card(
                html,
                "🔗",
                "Correlation Evidence",
                value(root, "correlationId", "Available"),
                "../../api/reports/enterprise-summary.json",
                "Open correlation data"
        );
        card(
                html,
                "✅",
                "Contract Validation",
                root.path("failedSteps").asInt(0) == 0 ? "Passed" : "Review required",
                "../../api/reports/enterprise-summary.json",
                "Open validation evidence"
        );
    }

    private static void appendPerformance(StringBuilder html, JsonNode root) {
        card(
                html,
                "📈",
                "Enterprise Performance Report",
                performanceSummary(root),
                "../../performance/reports/index.html",
                "Open performance dashboard"
        );
        card(
                html,
                "⚡",
                "k6 Workload Report",
                "Smoke workload available",
                "../../performance/k6/reports/smoke/index.html",
                "Open k6 report"
        );
        card(
                html,
                "📊",
                "JMeter Workload Report",
                "Independent workload available",
                "../../performance/jmeter/reports/smoke/index.html",
                "Open JMeter report"
        );
        card(
                html,
                "🏭",
                "Production Workload",
                root.path("requests").asInt(0) + " requests",
                "../../performance/reports/enterprise-summary.json",
                "Open production metrics"
        );
        card(
                html,
                "🚦",
                "Performance Quality Gate",
                value(root, "qualityGate", "Available"),
                "../../performance/reports/enterprise-summary.json",
                "Open gate evidence"
        );
    }

    private static void appendGeneric(StringBuilder html, String key) {
        card(
                html,
                "📂",
                "Capability Evidence",
                "Available",
                "../../" + escape(key) + "/reports/",
                "Open evidence"
        );
    }

    private static void appendFailureIntelligence(StringBuilder html, String key) {
        Path path = Path.of(key, "reports", "failure-showcase.json");

        if (!Files.isRegularFile(path)) {
            card(
                    html,
                    "🤖",
                    "AI Failure Intelligence",
                    "Not generated",
                    "#",
                    "No failure evidence"
            );
            return;
        }

        try {
            JsonNode failure = JsonMapper.getInstance().readTree(path.toFile());
            String confidence = failure.path("confidence").asText("");
            String diagnosis = failure.path("diagnosis").asText("AI-ready analysis available");

            String summary = confidence.isBlank()
                    ? diagnosis
                    : "Confidence " + confidence + "%";

            card(
                    html,
                    "🤖",
                    "AI Failure Intelligence",
                    summary,
                    "../../" + path,
                    "Open AI analysis"
            );
        } catch (Exception ignored) {
            card(
                    html,
                    "🤖",
                    "AI Failure Intelligence",
                    "Evidence available",
                    "../../" + path,
                    "Open AI analysis"
            );
        }
    }

    private static void appendAllure(StringBuilder html) {
        card(
                html,
                "📑",
                "Allure Evidence Repository",
                "Engineering evidence available",
                "../../build/allure-report/index.html",
                "Open Allure"
        );
    }

    private static void appendRawSummary(StringBuilder html, String key) {
        card(
                html,
                "🧾",
                "Raw Execution Contract",
                "Versioned JSON evidence",
                "../../" + escape(key) + "/reports/enterprise-summary.json",
                "Open raw summary"
        );
    }

    private static void card(
            StringBuilder html,
            String icon,
            String title,
            String status,
            String href,
            String action
    ) {
        html.append("""
                <article class="card"
                  style="display:flex;flex-direction:column;justify-content:space-between;min-height:190px">
                  <div>
                    <div style="font-size:30px;margin-bottom:12px">
                """)
                .append(escape(icon))
                .append("""
                    </div>
                    <div class="label">Evidence Asset</div>
                    <h3 style="margin:7px 0 8px">
                """)
                .append(escape(title))
                .append("""
                    </h3>
                    <div style="font-weight:700;color:#147d64">
                """)
                .append(escape(status))
                .append("""
                    </div>
                  </div>
                  <a style="margin-top:18px;padding:9px 12px;border:1px solid #f1b38f;
                     border-radius:7px;color:#d04a02;font-weight:750;text-decoration:none;
                     text-align:center"
                     href="
                """)
                .append(escape(href))
                .append("""
                " target="_blank" rel="noopener noreferrer">
                """)
                .append(escape(action))
                .append("</a></article>");
    }

    private static String healingSummary(JsonNode root) {
        int attempts = root.path("healingAttempts").asInt(0);
        int recovered = root.path("recoveredLocators").asInt(0);

        if (attempts == 0) {
            return "No healing required";
        }
        return recovered + " locator(s) recovered";
    }

    private static String browserSummary(JsonNode root) {
        int consoleErrors = root.path("consoleEntries").asInt(0);
        int pageErrors = root.path("pageErrors").asInt(0);

        return consoleErrors == 0 && pageErrors == 0
                ? "Browser diagnostics passed"
                : "Diagnostics require review";
    }

    private static String networkSummary(JsonNode root) {
        int failures = root.path("networkFailures").asInt(0);
        return failures == 0 ? "No network failures" : failures + " failure(s)";
    }

    private static String payloadSummary(JsonNode root) {
        long bytes = root.path("totalPayloadBytes").asLong(0);
        return bytes > 0 ? bytes + " bytes captured" : "Payload evidence available";
    }

    private static String performanceSummary(JsonNode root) {
        int requests = root.path("requests").asInt(0);
        double p95 = root.path("p95Ms").asDouble(0.0);

        if (requests == 0) {
            return "Performance evidence available";
        }
        return requests + " requests · P95 " + String.format("%.2f ms", p95);
    }

    private static String value(JsonNode root, String field, String fallback) {
        JsonNode node = root.get(field);
        if (node == null || node.isNull() || node.asText().isBlank()) {
            return fallback;
        }
        return node.asText();
    }

    private static String escape(Object value) {
        if (value == null) {
            return "";
        }
        return value.toString()
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&#39;");
    }
}
