package web.updr.demo;

import com.microsoft.playwright.*;
import org.testng.Assert;
import org.testng.annotations.Test;
import web.config.WebConfiguration;
import web.tests.base.BaseWebTest;

public class UpdrWebDemoTest extends BaseWebTest {
    private static final String BASE_URL=System.getProperty("updr.baseUrl","http://localhost:8090");
    @Override protected WebConfiguration createWebConfiguration(){WebConfiguration c=super.createWebConfiguration();c.setTraceEnabled(true);c.setSaveTraceOnSuccess(true);c.setVideoEnabled(true);c.setConsoleLogsEnabled(true);return c;}
    @Test(description="UPDR integrated Admin, mobile Inspector and QC enterprise journey")
    public void demonstrateUpdrIntegratedQualityJourney(){page().request().post(BASE_URL+"/api/demo/reset");adminSetup(page());inspectorInitialSubmission();qcReturn(page());inspectorCorrection();qcApproval(page());}
    private void waitText(Page p,String id,String token){p.waitForCondition(()->p.getByTestId(id).innerText().contains(token),new Page.WaitForConditionOptions().setTimeout(10_000));}
    private void adminSetup(Page p){p.navigate(BASE_URL+"/admin.html");p.getByTestId("create-template").click();waitText(p,"admin-status","ACTIVE");p.getByTestId("assign-template").click();waitText(p,"admin-status","assigned");Assert.assertTrue(p.getByTestId("admin-audit").innerText().contains("TEMPLATE_ASSIGNED"));}
    private void inspectorInitialSubmission(){try(BrowserContext mobile=browser().newContext(new Browser.NewContextOptions().setViewportSize(390,844).setIsMobile(true).setHasTouch(true))){Page p=mobile.newPage();p.navigate(BASE_URL+"/inspector.html");p.getByTestId("load-order").click();waitText(p,"order-id","UPDR-1001");Assert.assertTrue(p.getByTestId("property-summary").innerText().contains("MLS-88421"));p.getByTestId("damage-present").selectOption("YES");Assert.assertTrue(p.getByTestId("conditional-fields").isVisible());p.getByTestId("analyze-photo").click();waitText(p,"quality-score","72");p.getByTestId("duplicate-photo").click();waitText(p,"validation-status","Duplicate evidence rejected");p.getByTestId("confirm-ai").click();waitText(p,"validation-status","confirmed");p.getByTestId("analyze-voice").click();waitText(p,"voice-transcript","Water damage");p.getByTestId("autosave-fail").click();waitText(p,"sync-status","OFFLINE_PENDING_SYNC");p.getByTestId("autosave-retry").click();waitText(p,"sync-status","SYNCED");p.getByTestId("validate-inspection").click();waitText(p,"validation-status","VALIDATION_FAILED");p.getByTestId("replacement-photo").click();waitText(p,"quality-score","96");p.getByTestId("repair-estimate").fill("2500");p.getByTestId("moisture-source").selectOption("FAILED_WINDOW_SEAL");p.getByTestId("validate-inspection").click();waitText(p,"inspection-status","READY_TO_SUBMIT");p.getByTestId("submit-inspection").click();waitText(p,"inspection-status","QUEUED_FOR_QC");}}
    private void qcReturn(Page p){p.navigate(BASE_URL+"/qc.html");p.getByTestId("refresh-queue").click();waitText(p,"queue-list","INSP-1001");p.getByTestId("open-inspection").click();waitText(p,"qc-status","QUEUED_FOR_QC");Assert.assertTrue(p.getByTestId("inspection-evidence").innerText().contains("Quality 96"));p.getByTestId("return-inspection").click();waitText(p,"qc-status","RETURNED");}
    private void inspectorCorrection(){try(BrowserContext mobile=browser().newContext(new Browser.NewContextOptions().setViewportSize(390,844).setIsMobile(true).setHasTouch(true))){Page p=mobile.newPage();p.navigate(BASE_URL+"/inspector.html");p.getByTestId("load-order").click();waitText(p,"inspection-status","RETURNED");Assert.assertTrue(p.getByTestId("qc-comment-display").innerText().contains("closer"));p.getByTestId("damage-present").selectOption("YES");p.getByTestId("replacement-photo").click();waitText(p,"quality-score","96");p.getByTestId("repair-estimate").fill("2800");p.getByTestId("moisture-source").selectOption("FAILED_WINDOW_SEAL");p.getByTestId("submit-inspection").click();waitText(p,"inspection-status","RESUBMITTED");}}
    private void qcApproval(Page p){p.navigate(BASE_URL+"/qc.html");p.getByTestId("refresh-queue").click();waitText(p,"queue-list","RESUBMITTED");p.getByTestId("open-inspection").click();waitText(p,"qc-status","RESUBMITTED");p.getByTestId("approve-inspection").click();waitText(p,"qc-status","APPROVED");}
}
