package platform.core.event;

public enum PlatformEventType {
    EXECUTION_STARTED,
    EXECUTION_COMPLETED,
    CAPABILITY_STARTED,
    CAPABILITY_COMPLETED,
    CAPABILITY_FAILED,
    STEP_STARTED,
    STEP_COMPLETED,
    EVIDENCE_CAPTURED,
    FAILURE_DETECTED,
    HEALING_STARTED,
    HEALING_SUCCEEDED,
    RISK_CALCULATED,
    DASHBOARD_PUBLISHED,
    RELEASE_APPROVED
}
