package dashboard.enterprise.agent.connector.provider;
import com.fasterxml.jackson.databind.JsonNode; import com.fasterxml.jackson.databind.ObjectMapper; import core.json.JsonMapper;
import dashboard.enterprise.agent.connector.credential.CredentialResolver; import dashboard.enterprise.agent.connector.health.ConnectorHealthChecker; import dashboard.enterprise.agent.connector.model.*; import dashboard.enterprise.agent.model.AgentContext;
import java.net.URI; import java.net.http.*; import java.time.Duration; import java.util.*;
public abstract class AbstractLiveRestConnectorProvider implements EnterpriseConnectorProvider { protected static final ObjectMapper MAPPER=JsonMapper.getInstance(); private final ConnectorDefinition definition; private final ConnectorConnection connection; private final int priority; protected final CredentialResolver credentials; private final ConnectorHealthChecker healthChecker; private final HttpClient client;
 protected AbstractLiveRestConnectorProvider(ConnectorDefinition definition,ConnectorConnection connection,int priority,CredentialResolver credentials){this.definition=definition;this.connection=connection;this.priority=priority;this.credentials=credentials;this.healthChecker=new ConnectorHealthChecker(credentials);this.client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(10)).build();}
 public ConnectorDefinition definition(){return definition;} public ConnectorConnection connection(){return connection;} public int priority(){return priority;} public ConnectorHealth health(){return healthChecker.assess(definition,connection);} protected abstract HttpRequest buildRequest(ConnectorRequest request)throws Exception; protected abstract Map<String,Object> normalize(String capabilityId,JsonNode payload);
 public ConnectorResponse invoke(AgentContext context,ConnectorRequest request)throws Exception{if(health().status()!=ConnectorStatus.HEALTHY)throw new IllegalStateException("Connector is not configured: "+definition.connectorId());HttpResponse<String> response=client.send(buildRequest(request),HttpResponse.BodyHandlers.ofString());boolean ok=response.statusCode()>=200&&response.statusCode()<300;if(!ok)throw new IllegalStateException("Connector HTTP status: "+response.statusCode());JsonNode payload=response.body().isBlank()?MAPPER.createObjectNode():MAPPER.readTree(response.body());return new ConnectorResponse("mapaf.connector.response/v1",request.requestId(),definition.connectorId(),true,"Live connector request completed.",List.of("http-status:"+response.statusCode(),connection.endpoint()),normalize(request.capabilityId(),payload));}
 protected URI uri(String path){return URI.create(connection.endpoint().replaceAll("/$","")+path);} protected String secret(String alias){return definition.secrets().stream().filter(s->s.alias().equals(alias)).findFirst().flatMap(credentials::resolve).orElseThrow(()->new IllegalStateException("Missing secret: "+alias));}}
