baseUrl=https://httpbin.org
platform=android
appiumServerUrl=http://127.0.0.1:4723

androidDeviceName=emulator-5554
androidAppPath=apps/android/app-qa.apk

iosDeviceName=iPhone 15
iosAppPath=apps/ios/app-qa.ipa