baseUrl=http://httpbin.org
platform=android
appiumServerUrl=http://127.0.0.1:4723

androidDeviceName=emulator-5554
androidAppPath=apps/android/ApiDemos-release.apk

iosDeviceName=iPhone 15
iosAppPath=apps/ios/app-qa.ipa

execution=local

browserstackUserName=
browserstackAccessKey=

browserstackDeviceName=Samsung Galaxy S24
browserstackOsVersion=14.0

browserstackAppId=

browserstackProjectName=MAPAF
browserstackBuildName=Regression Build
browserstackSessionName=Android Test

