baseUrl=https://httpbin.org
platform=android
appiumServerUrl=http://127.0.0.1:4723

androidDeviceName=emulator-5554
androidAppPath=apps/android/ApiDemos-release.apk

iosDeviceName=iPhone 15
iosAppPath=apps/ios/app-qa.ipa

execution=local

browserstackUserName=BROWSERSTACK_USERNAME
browserstackAccessKey=Test*123$

browserstackDeviceName=Samsung Galaxy S24
browserstackOsVersion=14.0

browserstackAppId=

browserstackProjectName=MAPAF
browserstackBuildName=Regression Build
browserstackSessionName=Android Test

browserstackIosDeviceName=iPhone 15
browserstackIosOsVersion=17
browserstackIosAppId=${BROWSERSTACK_IOS_APP_ID}

claudeApiKey=${CLAUDE_API_KEY}
claudeModel=claude-3-5-sonnet-latest
claudeMaxTokens=1024
aiProvider=claude

