package dashboard.enterprise.agent.llm.tests;
import dashboard.enterprise.agent.connector.credential.EnvironmentCredentialResolver;import dashboard.enterprise.agent.llm.audit.*;import dashboard.enterprise.agent.llm.model.*;import dashboard.enterprise.agent.llm.policy.LlmPermission;import dashboard.enterprise.agent.llm.prompt.PromptLoader;import dashboard.enterprise.agent.llm.provider.*;import dashboard.enterprise.agent.llm.registry.*;import dashboard.enterprise.agent.llm.resolution.*;import dashboard.enterprise.agent.llm.runtime.LlmRuntime;import dashboard.enterprise.agent.llm.validation.StructuredOutputValidator;import dashboard.enterprise.agent.model.AgentContext;import dashboard.enterprise.agent.skillstudio.loader.FileSystemSkillLoader;import org.testng.Assert;import org.testng.annotations.Test;import java.nio.file.*;import java.util.*;
public final class LlmProviderPlatformTest{
 @Test public void shouldResolveReplayAndReturnStructuredOutput()throws Exception{var replay=new ReplayLlmProvider("replay-llm",50,Set.of("test-design.generate"),Map.of("test-design.generate",Map.of("scenarios",List.of("api","mobile"))));var reg=new InMemoryLlmProviderRegistry();reg.register(replay);var audit=new InMemoryLlmAuditStore();var runtime=new LlmRuntime(new LlmProviderResolver(reg),audit,new StructuredOutputValidator());var response=runtime.generate(new AgentContext(Path.of("."),"CORR-LLM-1","tester",Map.of()),request("","test-design.generate"),LlmPermission.AUTONOMOUS_WRITE,false,Set.of("scenarios"));Assert.assertTrue(response.successful());Assert.assertEquals(response.providerId(),"replay-llm");Assert.assertEquals(audit.events().size(),1);}
 @Test public void shouldPreferConfiguredProvider()throws Exception{var a=new ReplayLlmProvider("a",10,Set.of("summary.generate"),Map.of("summary.generate",Map.of("summary","a")));var b=new ReplayLlmProvider("b",90,Set.of("summary.generate"),Map.of("summary.generate",Map.of("summary","b")));var r=new InMemoryLlmProviderRegistry();r.register(a);r.register(b);Assert.assertEquals(new LlmProviderResolver(r).resolve(request("a","summary.generate")).providerId(),"a");}
 @Test(expectedExceptions=SecurityException.class) public void shouldRequireApprovalForHighImpactReasoning()throws Exception{var r=new InMemoryLlmProviderRegistry();r.register(new ReplayLlmProvider("replay",50,Set.of("release-recommendation.generate"),Map.of()));new LlmRuntime(new LlmProviderResolver(r),new InMemoryLlmAuditStore(),new StructuredOutputValidator()).generate(new AgentContext(Path.of("."),"c","u",Map.of()),request("","release-recommendation.generate"),LlmPermission.WRITE_WITH_APPROVAL,false,Set.of());}
 @Test public void shouldFallBackWhenLiveProviderIsUnavailable()throws Exception{var live=new OpenAiLlmProvider(new EnvironmentCredentialResolver(Map.of()));var replay=new ReplayLlmProvider("replay",20,Set.of("reasoning.generate"),Map.of("reasoning.generate",Map.of("answer","safe")));var fallback=new FallbackLlmProvider("openai-with-replay",List.of(live,replay));Assert.assertTrue(fallback.available());Assert.assertEquals(fallback.generate(new AgentContext(Path.of("."),"c","u",Map.of()),request("","reasoning.generate")).providerId(),"replay");}
 @Test public void shouldLoadPromptFromSkillStudio()throws Exception{var skill=new FileSystemSkillLoader().load(Path.of("src/test/resources/skill-studio/test-design"));var prompt=new PromptLoader().load(skill,"prompts/system.md");Assert.assertTrue(prompt.systemPrompt().contains("MAPAF Test Design Agent"));Assert.assertEquals(prompt.schemaVersion(),"mapaf.llm.prompt/v1");}
 private static LlmRequest request(String preferred,String capability){return new LlmRequest("mapaf.llm.request/v1","REQ-"+capability,capability,preferred,"system","user","{}",Map.of());}}
